### ISSUE TITLE
.rubocop.yml "Limits lines to 79 chars" but the max is set to 180

### ISSUE THREAD

**Issue by carstenhag** [discourse/onebox#262]
```
# Limit lines to 79 characters.
LineLength:
  Enabled: true
  Max: 180
```
